### ISSUE TITLE
bionic start throwing an error

### ISSUE THREAD

**Issue by cissemy** [BionicFramework/BionicCapacitorPlugin#4]
Hi,
I am the following error every time  i run bionic start :     
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\cisse\Application Data' is denied.

Thanks

**Comment by bmsantos** [comment]
Please make sure you are executing the command on a Blazor project.
"bionic start" needs to be executed within the project directory of the project.

If the directory is correct, then please check the directory permission. It seems something is preventing bionic from accessing that directory. Bionic needs to update some files in the current project directory.

You can see a video here on how to initialize Bionic on a Blazor project:
https://www.youtube.com/watch?v=_YRR6L2Pzks&list=PLLxOHqHInCELJjnvN_rCKx5pa_53Utjr7&index=2&t=0s

**Comment by doyleyoung** [comment]
No new information, closing...
